=== simicjan/java/NetBeansProjects/Ships/resources/ships.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified"  targetNamespace="http://www.artin.cz/ships/gen">
       <xs:element name="ships">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="ship" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="name" type="xs:string"></xs:element>
                                                 <xs:element name="class" type="xs:string"></xs:element>
                                                 <xs:element name="weight" type="xs:int"></xs:element>
                                                 <xs:element name="length" type="xs:int"></xs:element>
                                                 <xs:element name="width" type="xs:int"></xs:element>
                                                 <xs:element name="dateOfCreation" type="xs:date"></xs:element>
                                             </xs:sequence>
                                      </xs:complexType>
                               </xs:element>
                        </xs:sequence>
                 </xs:complexType>
          </xs:element>
   </xs:schema>

=== simicjan/java/NetBeansProjects/Ships/resources/ships_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ships xmlns="http://www.artin.cz/ships/gen" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.artin.cz/ships/gen ships.xsd">
    <ship>
        <name>Aaron Manby</name>
        <class>cz.artin.ships.model.SteamShip</class>
        <weight>20</weight>
        <length>120</length>
        <width>15</width>
        <dateOfCreation>2011-10-26</dateOfCreation>
    </ship>
    <ship>
        <name>Yamal</name>
        <class>cz.artin.ships.model.IceBreaker</class>
        <weight>30</weight>
        <length>99</length>
        <width>12</width>
        <dateOfCreation>2011-10-13</dateOfCreation>
    </ship>
    <ship>
        <name>Titanic</name>
        <class>cz.artin.ships.model.SteamShip</class>
        <weight>30</weight>
        <length>140</length>
        <width>25</width>
        <dateOfCreation>2012-10-26</dateOfCreation>
    </ship>
</ships>
